### ISSUE TITLE
Updating related fields from memoized selector

### ISSUE THREAD

**Issue by talolard** [redux-orm/redux-orm#218] opened 2018-07-03 12:45 UTC
Hi,
We're super happy to see this project moving again! We're still a few versions back, and ran into an issue. 
Anyway, we have model A and model B. B has a foreign key to A. 

At some point we call an instance of A and dispatch an action to add new B's to it. 

We're getting A via a memoized selector, and it looks like it doesn't get an indication that a B was added, so A.bs.toModelArray doesn't update with the B that was added. 

I couldn't tell if this is a known issue, by design or something resolved recently. 

We'd like to know if the newer versions address this or is their something we can do 
Thanks

**Comment by haveyaseen** [comment] 2018-07-03 17:33
If I understand your use-case correctly, his should not be necessary at all. What are your `A.fields` and `B.fields`? And how does the selector look like? If `a` is an instance of `A` and you access `a.bs` within the selector, then your selector should be called again if you create/update/delete an instance of `B`.

**Comment by talolard** [comment] 2018-07-04 07:44
Thanks. 
I'll switch from A and B to the actual code.
I have two models, Project and Datset and a Dataset has a FK to a Project

```es6
class Project extends Model {
  toString() {
    return `Project: ${this.id}`;
  }
  static reducer(action, Project, session) {
    switch (action.type) {
      case RECEIVE_PROJECT: {
        const { id, name } = action.payload;
        Project.create({ id, name });
        break;
      }

      default:
        break;
    }
  }
}
Project.modelName = 'Project';
Project.fields = {
  id: attr(),
  name: attr(),
  touched: attr()
};
```

The dataset

```es6
class Dataset extends Model {
  toString() {
    return `Dataset: ${this.id}`;
  }

  static reducer(action, Dataset, session) {
    switch (action.type) {
      case CREATE_DATASET: {
        Dataset.upsert(action.payload);
        break;
      }
      default:
        return undefined;
    }
  }
}
Dataset.modelName = 'Dataset';
Dataset.fields = {
  id: attr(),
  name: attr(),
  id_field: attr(),
  aggregation_field: attr(),
  order_field: attr(),
  content_field: attr(),
  project: fk('Project', 'datasets')
};
```

The project selector

```es6
const _projectSelector = createSelector(
  orm,
  state => state.orm,
  session => {
    return session.Project.all().toModelArray();
  }
);

```
And then, in a connected component that uses that selector (and takes the first element in the array)  I have
```es6
        {props.project.datasets
          .toModelArray()
          .map(dataset => (
            <ListGroupItem key={dataset.id}>{dataset.name}</ListGroupItem>
          ))}


```

or more simply this
`{props.project.datasets.count()}`

Neither of which updates when I add a new dataset. 

I've confirmed the dataset is updated with the proper id of the project, and the project exists in the orm with that id. 

Thanks

**Comment by haveyaseen** [comment] 2018-07-04 11:15
Using models and relationship accessors outside of selectors is not supported by design. In this case specifically you are first executing the selector and accessing `project.datasets` afterwards. Redux-ORM has no way of knowing that you care about `project.datasets` so your `_projectSelector` won't be re-executed when you are performing changes on the `Dataset` model only.

Please use `session.Project.all().toRefArray()` and `session.Dataset.all().toRefArray()`  instead. For convenience, you could also create a different selector that returns the datasets for each project as references:
```javascript
const _projectDatasets = createSelector(
  orm,
  state => state.orm,
  session => session.Project.toModelArray().reduce((map, project) => ({
    ...map,
    [project.id]: project.datasets.toRefArray(),
  }), {})
);
```
And then in your component:
```javascript
        {props.projectDatasets[props.project.id]
          .map(dataset => (
            <ListGroupItem key={dataset.id}>{dataset.name}</ListGroupItem>
          ))}
```

**Comment by talolard** [comment] 2018-07-04 18:32
Oh that's elegant. Thanks. 
As an aside, we've been doing it the wrong way in production for about 6 months and it worked fine until now (when we turne don memoization). The convenience of having a .datasets() on a project (and similar concepts) has been huge.

**Comment by haveyaseen** [comment] 2019-04-15 17:39
Closing in favor or #253.

**Closed by haveyaseen** 2019-04-15 17:39 UTC
Labels: type: Question

**Comment by Eddie-CooRo** [comment] 2019-05-11 12:57
Hi, I wonder if we can reopen this issue.
I have a situation that may be related to this one.
Consider having a selector which returns the First Model named Rooms, and another selector which uses this selector as a dependency and returns all messages of that specific room. So we can write something like this:

```
const getRoomID = (state, props) => props.roomID;
const getRoom = createSelector(orm, dbSelector, getRoomID, (session, roomID) => {
  const room = session.Rooms.withId(roomID);
  return room; 
});
const getRoomMessages = createSelector(orm, dbSelector, getRoom, (session, room) => room.messages.all().toRefArray() );
```

But the problem is that either room or data may not exist and we want our app to be fault-tolerant. So we should return a default case when either of them doesn't exist.
```
const getRoom = createSelector(..., (session, roomID) => {
  return session.Rooms.withId(roomID) || {};
});
const getRoomMessages = createSelector(..., (session, room) => room.messages ? room.messages.all().toRefArray() : [] );
```

But now if the room doesn't exist the first time we use the `getRoomMessages` selector, `room.messages.all().toRefArray()` never gets executed, and even if we add new messages to the room messages field, the result of `getRoomsMessages` always will be an empty array.
It would be nice if when the user queries `room.messages,` *redux-orm* could mark it as accessed and whenever a new model related to the room gets created, the selector executes again.

**Comment by haveyaseen** [comment] 2019-05-12 09:49
@Eddie-CooRo The probleme here, again, is returning models from selectors. Because this happens so often I'm starting to think that we should actually forbid returning model instances by throwing an error.

Selectors were not composable the way you did it. You would have had to call `session.Rooms.withId()` within `getRoomMessages`. Then both `room.ref` and `room.messages` get marked as accessed as you described (conceptually). Now, you no longer need to do that as v0.14.0-rc.0 accounts for this :slightly_smiling_face:
